## Analyzing Bacterial and Viral Bioinformatics Resource Center (BV-BRC) Database
File: input/data/bvbrc/BVBRC_genome_20260327.csv

Downloaded on: March 27, 2026

Url: https://www.bv-brc.org/view/Virus/10239

In [1]:
import pandas as pd
import os

In [2]:
dataset_csv_filepath = os.path.join(os.getcwd(), "..", "..", "..","..", "..", "input/data/bvbrc/BVBRC_genome_20260327.csv")

In [3]:
df = pd.read_csv(dataset_csv_filepath)

/tmp/ipykernel_4034253/3262779000.py:1: DtypeWarning: Columns (6,16,17,20,21,24,25,26,27,29,30,31,32,34,35,37,39,40,41,42,44,46,47,48,64,66,67,69,71,79,80,81,83,84,85,86,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(dataset_csv_filepath)

In [9]:
df.shape

(2500000, 90)

In [4]:
df.columns

Index(['Genome ID', 'Genome Name', 'Other Names', 'NCBI Taxon ID',
       'Taxon Lineage IDs', 'Taxon Lineage Names', 'Superkingdom', 'Kingdom',
       'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species',
       'Genome Status', 'Strain', 'Serovar', 'Biovar', 'Pathovar', 'MLST',
       'Segment', 'Subtype', 'H_type', 'N_type', 'H1 Clade Global',
       'H1 Clade US', 'H5 Clade', 'pH1N1-like', 'Lineage', 'Clade', 'Subclade',
       'Other Typing', 'Culture Collection', 'Type Strain', 'Reference',
       'Genome Quality', 'Completion Date', 'Publication', 'Authors',
       'BioProject Accession', 'BioSample Accession', 'Assembly Accession',
       'SRA Accession', 'GenBank Accessions', 'Sequencing Center',
       'Sequencing Status', 'Sequencing Platform', 'Sequencing Depth',
       'Assembly Method', 'Chromosome', 'Plasmids', 'Contigs', 'Size',
       'GC Content', 'Contig L50', 'Contig N50', 'TRNA', 'RRNA', 'Mat Peptide',
       'CDS', 'Coarse Consistency', 'Fine Consistency', 'CheckM Contamination',
       'CheckM Completeness', 'Genome Quality Flags', 'Isolation Source',
       'Isolation Comments', 'Collection Date', 'Collection Year', 'Season',
       'Isolation Country', 'State/Province', 'County', 'City',
       'Geographic Group', 'Geographic Location', 'Other Environmental',
       'Host Name', 'Host Common Name', 'Host Sex', 'Host Age', 'Host Health',
       'Host Group', 'Lab Host', 'Passage', 'Other Clinical',
       'Additional Metadata', 'Comments', 'Date Inserted', 'Date Modified'],
      dtype='object')

In [5]:
df

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,...,Host Age,Host Health,Host Group,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified
0,1.000288e+06,Influenza A virus (A/canine/Zhejiang/1/2010(H3...,NaN,1000288,10239;2559587;2732396;2497569;2497571;2497577;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Insthoviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-03-19T10:53:14.732Z,2021-03-19T10:53:14.732Z
1,1.000288e+06,Influenza A virus (A/canine/Zhejiang/1/2010(H3...,NaN,1000288,10239;2559587;2732396;2497569;2497571;2497577;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Insthoviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-03-19T10:55:15.334Z,2021-03-19T10:55:15.334Z
2,1.000288e+06,Influenza A virus (A/canine/Zhejiang/1/2010(H3...,NaN,1000288,10239;2559587;2732396;2497569;2497571;2497577;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Insthoviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-03-19T10:53:14.348Z,2021-03-19T10:53:14.348Z
3,1.000288e+06,Influenza A virus (A/canine/Zhejiang/1/2010(H3...,NaN,1000288,10239;2559587;2732396;2497569;2497571;2497577;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Insthoviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-03-19T10:53:14.484Z,2021-03-19T10:53:14.484Z
4,1.000289e+06,Influenza A virus (A/canine/Zhejiang/1/2010(H3...,NaN,1000288,10239;2559587;2732396;2497569;2497571;2497577;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Insthoviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-03-19T10:53:15.072Z,2021-03-19T10:53:15.072Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2499995,1.167618e+04,Human immunodeficiency virus 1 pci225,NaN,11676,10239;2559587;2732397;2732409;2732514;2169561;...,Viruses;Riboviria;Pararnavirae;Artverviricota;...,NaN,Pararnavirae,Artverviricota,Revtraviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-11T12:06:48.214Z,2025-12-11T12:06:48.214Z
2499996,1.167618e+04,Human immunodeficiency virus 1 pci227,NaN,11676,10239;2559587;2732397;2732409;2732514;2169561;...,Viruses;Riboviria;Pararnavirae;Artverviricota;...,NaN,Pararnavirae,Artverviricota,Revtraviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-11T12:06:47.997Z,2025-12-11T12:06:47.997Z
2499997,1.167618e+04,Human immunodeficiency virus 1 pci229,NaN,11676,10239;2559587;2732397;2732409;2732514;2169561;...,Viruses;Riboviria;Pararnavirae;Artverviricota;...,NaN,Pararnavirae,Artverviricota,Revtraviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-11T12:06:48.100Z,2025-12-11T12:06:48.100Z
2499998,1.167618e+04,Human immunodeficiency virus 1 pci230,NaN,11676,10239;2559587;2732397;2732409;2732514;2169561;...,Viruses;Riboviria;Pararnavirae;Artverviricota;...,NaN,Pararnavirae,Artverviricota,Revtraviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-11T12:06:51.307Z,2025-12-11T12:06:51.307Z
2499999,1.167618e+04,Human immunodeficiency virus 1 pci192,NaN,11676,10239;2559587;2732397;2732409;2732514;2169561;...,Viruses;Riboviria;Pararnavirae;Artverviricota;...,NaN,Pararnavirae,Artverviricota,Revtraviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-11T12:06:51.406Z,2025-12-11T12:06:51.406Z

In [11]:
df_1 = df[~df["GenBank Accessions"].isna()]
df_1.shape

(2438268, 90)

In [15]:
df_1["Host Common Name"]

0          Dog
1          Dog
2          Dog
3          Dog
4          Dog
          ...
2499995    NaN
2499996    NaN
2499997    NaN
2499998    NaN
2499999    NaN
Name: Host Common Name, Length: 2438268, dtype: object

In [16]:
df_1["Genome Status"].value_counts()

Partial       1882312
Complete       449467
WGS            105405
Deprecated       1000
Name: Genome Status, dtype: int64

In [26]:
df_2 = df_1[df_1["Database"] == "GenBank"]
df_2.shape

(777873, 36)

In [28]:
df_2["DetectionMethod"].value_counts()

PCR/Sequencing    777873
Name: DetectionMethod, dtype: int64

In [29]:
df_2

,Host,Virus,HostTaxID,VirusTaxID,HostNCBIResolved,VirusNCBIResolved,ICTVRatified,HostGenus,HostFamily,HostOrder,...,ReleaseMonth,ReleaseDay,CollectionYear,CollectionMonth,CollectionDay,AssocID,DatabaseDOI,Release_Date,Collection_Date,NCBIAccession
0,NaN,NaN,10040.0,NaN,True,NaN,False,peromyscus,cricetidae,rodentia,...,11.0,26.0,2006.0,NaN,NaN,NaN,NaN,2011-11-26,2006,JN196141.1
1,NaN,NaN,10040.0,NaN,True,NaN,False,peromyscus,cricetidae,rodentia,...,11.0,26.0,2006.0,NaN,NaN,NaN,NaN,2011-11-26,2006,JN196144.1
2,NaN,NaN,10040.0,NaN,True,NaN,False,peromyscus,cricetidae,rodentia,...,11.0,26.0,2006.0,NaN,NaN,NaN,NaN,2011-11-26,2006,JN196145.1
3,NaN,NaN,10040.0,NaN,True,NaN,False,peromyscus,cricetidae,rodentia,...,11.0,26.0,2006.0,NaN,NaN,NaN,NaN,2011-11-26,2006,JN196139.1
4,NaN,NaN,10040.0,NaN,True,NaN,False,peromyscus,cricetidae,rodentia,...,11.0,26.0,2006.0,NaN,NaN,NaN,NaN,2011-11-26,2006,JN196143.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
851182,zygodontomys brevicauda,zygodontomys brevicauda hepacivirus 2,157541.0,2875887.0,True,True,False,zygodontomys,cricetidae,rodentia,...,9.0,19.0,NaN,NaN,NaN,NaN,NaN,2021-09-19,NaN,MT732112.1
851183,zygodontomys brevicauda,zygodontomys brevicauda polyomavirus,157541.0,2875888.0,True,True,False,zygodontomys,cricetidae,rodentia,...,9.0,19.0,NaN,NaN,NaN,NaN,NaN,2021-09-19,NaN,MT732104.1
851184,zygodontomys cherriei,orthohantavirus sp. 'necocliense',218840.0,3052488.0,True,True,False,zygodontomys,cricetidae,rodentia,...,2.0,15.0,2008.0,NaN,NaN,NaN,NaN,2012-02-15,2008,"JN717148.1, JN717149.1"
851185,zygodontomys cherriei,orthohantavirus sp. 'necocliense',218840.0,3052488.0,True,True,False,zygodontomys,cricetidae,rodentia,...,8.0,29.0,2008.0,3.0,16.0,NaN,NaN,2015-08-29,2008-03-16,KM196124.1
851186,zygodontomys cherriei,orthohantavirus sp. 'necocliense',218840.0,3052488.0,True,True,False,zygodontomys,cricetidae,rodentia,...,8.0,29.0,2010.0,7.0,31.0,NaN,NaN,2015-08-29,2010-07-31,KM196123.1

In [30]:
df_2.columns

Index(['Host', 'Virus', 'HostTaxID', 'VirusTaxID', 'HostNCBIResolved',
       'VirusNCBIResolved', 'ICTVRatified', 'HostGenus', 'HostFamily',
       'HostOrder', 'HostClass', 'HostOriginal', 'VirusGenus', 'VirusFamily',
       'VirusOrder', 'VirusClass', 'VirusOriginal', 'HostFlagID',
       'DetectionMethod', 'DetectionOriginal', 'Database', 'DatabaseVersion',
       'PublicationYear', 'ReferenceText', 'PMID', 'ReleaseYear',
       'ReleaseMonth', 'ReleaseDay', 'CollectionYear', 'CollectionMonth',
       'CollectionDay', 'AssocID', 'DatabaseDOI', 'Release_Date',
       'Collection_Date', 'NCBIAccession'],
      dtype='object')

In [43]:
select_columns = ["Host", "Virus", "HostTaxID", "VirusTaxID", "NCBIAccession"]
final_df = df_2[select_columns]
final_df

,Host,Virus,HostTaxID,VirusTaxID,NCBIAccession
0,NaN,NaN,10040.0,NaN,JN196141.1
1,NaN,NaN,10040.0,NaN,JN196144.1
2,NaN,NaN,10040.0,NaN,JN196145.1
3,NaN,NaN,10040.0,NaN,JN196139.1
4,NaN,NaN,10040.0,NaN,JN196143.1
...,...,...,...,...,...
851182,zygodontomys brevicauda,zygodontomys brevicauda hepacivirus 2,157541.0,2875887.0,MT732112.1
851183,zygodontomys brevicauda,zygodontomys brevicauda polyomavirus,157541.0,2875888.0,MT732104.1
851184,zygodontomys cherriei,orthohantavirus sp. 'necocliense',218840.0,3052488.0,"JN717148.1, JN717149.1"
851185,zygodontomys cherriei,orthohantavirus sp. 'necocliense',218840.0,3052488.0,KM196124.1
851186,zygodontomys cherriei,orthohantavirus sp. 'necocliense',218840.0,3052488.0,KM196123.1

In [44]:
final_df.rename(columns={
    "Host": "source_host_species_name",
    "Virus": "source_virus_species_name",
    "HostTaxID": "source_host_species_taxid",
    "VirusTaxID": "source_virus_species_taxid",
    "NCBIAccession": "ncbi_genbank_accession" 
}, inplace=True)

/tmp/ipykernel_4030673/2420785284.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.rename(columns={

In [45]:
final_df["dataset_source"] = "virion"

/tmp/ipykernel_4030673/78179959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["dataset_source"] = "virion"

In [46]:
final_df.to_csv(os.path.join(os.getcwd(), "..", "..", "..","..", "..", "input/data/virion/20260326/virion_processed_20260327.csv"), index=False)

## VBRC