In [1]:
import pandas as pd
import os
import numpy as np
import math
import pytaxonkit
import subprocess
import json

In [50]:
!datasets download virus genome accession "AF538689.1"  --include protein --filename "test-data.zip"

Downloading: test-data.zip    1.52kB 9.18MB/s
Downloading: test-data.zip    1.52kB 9.18MB/s
Downloading: test-data.zip    4.07kB valid data package
Validating package files [================================================] 100% 5/5

In [2]:
dataset_csv_filepath = os.path.join(os.getcwd(), "..", "..", "..","..", "..", "input/data/bvbrc/BVBRC_reference_genome_20260429.csv")
df = pd.read_csv(dataset_csv_filepath, low_memory=False)
print(f"Dataset size: {df.shape}")
df.columns

Dataset size: (15731, 90)

Index(['Genome ID', 'Genome Name', 'Other Names', 'NCBI Taxon ID',
       'Taxon Lineage IDs', 'Taxon Lineage Names', 'Superkingdom', 'Kingdom',
       'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species',
       'Genome Status', 'Strain', 'Serovar', 'Biovar', 'Pathovar', 'MLST',
       'Segment', 'Subtype', 'H_type', 'N_type', 'H1 Clade Global',
       'H1 Clade US', 'H5 Clade', 'pH1N1-like', 'Lineage', 'Clade', 'Subclade',
       'Other Typing', 'Culture Collection', 'Type Strain', 'Reference',
       'Genome Quality', 'Completion Date', 'Publication', 'Authors',
       'BioProject Accession', 'BioSample Accession', 'Assembly Accession',
       'SRA Accession', 'GenBank Accessions', 'Sequencing Center',
       'Sequencing Status', 'Sequencing Platform', 'Sequencing Depth',
       'Assembly Method', 'Chromosome', 'Plasmids', 'Contigs', 'Size',
       'GC Content', 'Contig L50', 'Contig N50', 'TRNA', 'RRNA', 'Mat Peptide',
       'CDS', 'Coarse Consistency', 'Fine Consistency', 'CheckM Contamination',
       'CheckM Completeness', 'Genome Quality Flags', 'Isolation Source',
       'Isolation Comments', 'Collection Date', 'Collection Year', 'Season',
       'Isolation Country', 'State/Province', 'County', 'City',
       'Geographic Group', 'Geographic Location', 'Other Environmental',
       'Host Name', 'Host Common Name', 'Host Sex', 'Host Age', 'Host Health',
       'Host Group', 'Lab Host', 'Passage', 'Other Clinical',
       'Additional Metadata', 'Comments', 'Date Inserted', 'Date Modified'],
      dtype='object')

In [3]:
df

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,...,Host Age,Host Health,Host Group,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified
0,1000373.10,Rosellinia necatrix quadrivirus 1 W1118,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-06T11:05:04.123Z,2025-12-06T11:05:04.123Z
1,1000373.40,Rosellinia necatrix quadrivirus 1 W1075,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-06T08:01:47.037Z,2025-12-06T08:01:47.037Z
2,1000373.50,Rosellinia necatrix quadrivirus 1 W1075,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-06T08:01:47.164Z,2025-12-06T08:01:47.164Z
3,1000411.30,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:04:18.329Z,2021-01-23T22:04:18.329Z
4,1000411.40,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:06:18.856Z,2021-01-23T22:06:18.856Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15726,999729.23,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:40:21.986Z,2022-03-12T21:40:21.986Z
15727,999729.24,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:34:20.054Z,2022-03-12T21:34:20.054Z
15728,999729.25,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:49:25.104Z,2022-03-12T21:49:25.104Z
15729,999729.35,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-05-01T01:51:20.496Z,2022-05-01T01:51:20.496Z
15730,999883.50,Lausannevirus 7715,NaN,999883,10239;2732004;2732005;2732007;2732523;2732555;...,Viruses;Varidnaviria;Bamfordvirae;Nucleocytovi...,Viruses,Bamfordvirae,Nucleocytoviricota,Megaviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-16T15:15:58.376Z,2025-12-16T15:15:58.376Z

In [4]:
df["Host Group"].value_counts()

Nonhuman Mammal    1395
Bacteria            882
Plant               779
Insect              770
Human               610
Avian               371
Tick                298
Lab                  79
Fish                 71
Reptile              35
Sea Mammal           25
Crustaceans          20
Amphibian             2
Fungi                 1
Name: Host Group, dtype: int64

In [5]:
df["Host Name"].nunique()

3771

In [26]:
df[df["Host Name"].isna()][["Genome Name", "GenBank Accessions"]]

                               Genome Name GenBank Accessions
33                     Ljungan virus M1146           AF538689
35             Bos taurus papillomavirus 7           DQ217793
45               Simian sapelovirus 1 2383          NC_004451
46               Simian sapelovirus 1 2383           AY064708
47               Porcine sapelovirus 1 V13           AF406813
...                                    ...                ...
15631  Plutella xylostella granulovirus K1           AF270937
15633              Pseudomonas phage phi15           FR823298
15634              Tanapox virus TPV-Kenya           EF420156
15672      Titi monkey adenovirus ECC-2011           HQ913600
15673      Titi monkey adenovirus ECC-2011          NC_020487

[4349 rows x 2 columns]

In [7]:
print(df["Host Name"].nunique())
print(df["Host Common Name"].nunique())

3771
369

In [10]:
print(sum(df["Host Name"].isna()))
print(sum(df["Host Common Name"].isna()))
print(sum(df["Host Name"].isna() & ~df["Host Common Name"].isna() ))

4349
10393
34

In [6]:
df[df["Host Name"].isna() & ~df["Host Common Name"].isna()][["Genome ID", "GenBank Accessions", "Host Name", "Host Common Name"]]

          Genome ID GenBank Accessions Host Name Host Common Name
125    1.024541e+04          NC_006998       NaN         Lab host
126    1.025430e+04           AY243312       NaN         Lab host
519    1.078429e+04          NC_001540       NaN         Lab host
520    1.078829e+04          NC_001539       NaN         Lab host
521    1.079439e+04          NC_001510       NaN         Lab host
522    1.079440e+04             J02275       NaN         Lab host
951    1.133292e+06           JN939331       NaN         Lab host
952    1.133294e+06           JN939332       NaN         Lab host
1189   1.168745e+06           JQ797329       NaN         Lab host
2082   1.327970e+06           KC821606       NaN         Lab host
2083   1.327971e+06           KC821607       NaN         Lab host
2084   1.327972e+06           KC821608       NaN         Lab host
2085   1.327973e+06           KC821609       NaN         Lab host
2086   1.327977e+06           KC821613       NaN         Lab host
2087   1.327978e+06           KC821614       NaN         Lab host
2088   1.327981e+06           KC821617       NaN         Lab host
2089   1.327982e+06           KC821618       NaN         Lab host
2090   1.327983e+06           KC821619       NaN         Lab host
2091   1.327984e+06           KC821620       NaN         Lab host
2092   1.327986e+06           KC821622       NaN         Lab host
2093   1.327988e+06           KC821623       NaN         Lab host
2094   1.327991e+06           KC821624       NaN         Lab host
2095   1.328030e+06           KC821632       NaN         Lab host
2096   1.328031e+06           KC821633       NaN         Lab host
5729   1.972567e+06           JF911700       NaN         Lab host
5730   1.972568e+06          NC_025378       NaN         Lab host
8879   2.526028e+05          NC_006148       NaN         Lab host
13607  4.369115e+05          NC_011050       NaN         Lab host
14315  5.850604e+05           HB426768       NaN           Patent
14316  5.850613e+05           HC084988       NaN           Patent
14317  5.850634e+05           HC085020       NaN           Patent
14319  5.850653e+05           HC000816       NaN           Patent
14320  5.850684e+05           HC000847       NaN           Patent
14321  5.850743e+05           HC000785       NaN           Patent

In [15]:
sum(~df["Host Name"].isna())

11382

In [7]:
df = df[~df["Host Name"].isna()]
df.shape

(11382, 90)

In [9]:
!datasets summary taxonomy taxon "Homo sapiens, Sus scrofa"

{"reports": [{"query":["Homo sapiens"],"taxonomy":{"children":[741158,63221],"classification":{"class":{"id":40674,"name":"Mammalia"},"domain":{"id":2759,"name":"Eukaryota"},"family":{"id":9604,"name":"Hominidae"},"genus":{"id":9605,"name":"Homo"},"kingdom":{"id":33208,"name":"Metazoa"},"order":{"id":9443,"name":"Primates"},"phylum":{"id":7711,"name":"Chordata"},"species":{"id":9606,"name":"Homo sapiens"}},"counts":[{"count":2497,"type":"COUNT_TYPE_ASSEMBLY"},{"count":193866,"type":"COUNT_TYPE_GENE"},{"count":701,"type":"COUNT_TYPE_tRNA"},{"count":785,"type":"COUNT_TYPE_rRNA"},{"count":168,"type":"COUNT_TYPE_snRNA"},{"count":4,"type":"COUNT_TYPE_scRNA"},{"count":1201,"type":"COUNT_TYPE_snoRNA"},{"count":20624,"type":"COUNT_TYPE_PROTEIN_CODING"},{"count":22583,"type":"COUNT_TYPE_ncRNA"},{"count":128261,"type":"COUNT_TYPE_BIOLOGICAL_REGION"},{"count":843,"type":"COUNT_TYPE_OTHER"}],"curator_common_name":"human","current_scientific_name":{"authority":"Linnaeus, 1758","name":"Homo sapiens"},"current_scientific_name_is_formal":true,"genomic_moltype":"dsDNA","group_name":"primates","parents":[1,131567,2759,33154,33208,6072,33213,33511,7711,89593,7742,7776,117570,117571,8287,1338369,32523,32524,40674,32525,9347,1437010,314146,9443,376913,314293,9526,314295,9604,207598,9605],"rank":"SPECIES","tax_id":9606}},{"query":[" Sus scrofa"],"taxonomy":{"children":[2485929,490583,310261,415978,375579,309914,1611878,1611880,1611879,375578,1017268,9825,309913,291050,310260,1170810],"classification":{"class":{"id":40674,"name":"Mammalia"},"domain":{"id":2759,"name":"Eukaryota"},"family":{"id":9821,"name":"Suidae"},"genus":{"id":9822,"name":"Sus"},"kingdom":{"id":33208,"name":"Metazoa"},"order":{"id":91561,"name":"Artiodactyla"},"phylum":{"id":7711,"name":"Chordata"},"species":{"id":9823,"name":"Sus scrofa"}},"counts":[{"count":54,"type":"COUNT_TYPE_ASSEMBLY"},{"count":45429,"type":"COUNT_TYPE_GENE"},{"count":554,"type":"COUNT_TYPE_tRNA"},{"count":6,"type":"COUNT_TYPE_rRNA"},{"count":20833,"type":"COUNT_TYPE_PROTEIN_CODING"},{"count":6022,"type":"COUNT_TYPE_ncRNA"},{"count":141,"type":"COUNT_TYPE_OTHER"}],"curator_common_name":"pig","current_scientific_name":{"authority":"Linnaeus, 1758","name":"Sus scrofa"},"current_scientific_name_is_formal":true,"genomic_moltype":"dsDNA","group_name":"even-toed ungulates \u0026 whales","has_type_material":true,"parents":[1,131567,2759,33154,33208,6072,33213,33511,7711,89593,7742,7776,117570,117571,8287,1338369,32523,32524,40674,32525,9347,1437010,314145,91561,35497,9821,9822],"rank":"SPECIES","tax_id":9823}}],"total_count": 2}

In [47]:
VERTEBRATA_TAX_ID = 7742

def get_host_metadata(host_names):
    host_metadata = {}

    n = len(host_names)
    step = 100
    for i in range(0, n, step):
    #for virus_name in virus_names:
        try:
            start = i
            end = i + step if n > i + step else n
            host_names_list = ",".join(host_names[start : end])
            output = subprocess.run(["datasets", "summary", "taxonomy", "taxon", host_names_list], capture_output=True)
            #tax_json = json.loads(output.stdout)["reports"][0]["taxonomy"]["classification"]
            output_json = json.loads(output.stdout)
            reports = output_json["reports"]
            report_count = int(output_json["total_count"])
            print(f"{start} : {end} > {report_count}")
            for report in reports:
                host_name = report["query"][0]
                tax_json = report["taxonomy"]
                classification_json = tax_json["classification"]
                metadata = {}
                if "species" in classification_json:
                    metadata["species_tax_name"] = classification_json["species"]["name"]
                    metadata["species_tax_id"] = classification_json["species"]["id"]
    
                if "genus" in classification_json:
                    metadata["genus_tax_name"] = classification_json["genus"]["name"]
                    metadata["genus_tax_id"] = classification_json["genus"]["id"]
    
                if "family" in tax_json:
                    metadata["family_tax_name"] = classification_json["family"]["name"]
                    metadata["family_tax_id"] = classification_json["family"]["id"]
    
                parents = tax_json["parents"]
                if VERTEBRATA_TAX_ID in parents:
                    metadata["is_vertebrate"] = True
                else:
                    metadata["is_vertebrate"] = False
                    
                host_metadata[host_name] = metadata
        except Exception as e:
            print(e)
    return host_metadata

In [13]:
df["host_name_cleaned"] = df["Host Name"].apply(lambda x: " ".join(x.split(" ")[:2]))

/tmp/ipykernel_1450585/3428461402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["host_name_cleaned"] = df["Host Name"].apply(lambda x: " ".join(x.split(" ")[:2]))

In [16]:
df["Host Name"].nunique()

3771

In [17]:
df["Host Name"].value_counts()

Homo sapiens                           577
Mycobacterium smegmatis mc2 155        172
Escherichia coli                       131
Klebsiella pneumoniae                  118
Pseudomonas aeruginosa                  85
                                      ...
Salmo salar l. (atlantic salmon)         1
Cicer arietinum voucher dar 76857        1
Cicer arietinum voucher brip 52877a      1
Cicer arietinum voucher brip 52878a      1
Digitaria didactyla willd                1
Name: Host Name, Length: 3771, dtype: int64

In [14]:
df["host_name_cleaned"].nunique()

2635

In [15]:
df["host_name_cleaned"].value_counts()

Homo sapiens               579
Escherichia coli           302
Mycobacterium smegmatis    183
Klebsiella pneumoniae      174
Pseudomonas aeruginosa     143
                          ...
Feral pigeon                 1
Cercopithecus mitis          1
Datura inoxia                1
Ictalurus punctatus          1
Rhododendron maximum         1
Name: host_name_cleaned, Length: 2635, dtype: int64

In [48]:
hosts = df["host_name_cleaned"].unique()

In [ ]:
host_metadata = get_host_metadata(hosts)

0 : 100 > 79
100 : 200 > 84
200 : 300 > 81
300 : 400 > 92
400 : 500 > 90

In [38]:
host_metadata

{'Vernonia cinerea': {'species_tax_name': 'Cyanthillium cinereum',
  'species_tax_id': 211151,
  'genus_tax_name': 'Cyanthillium',
  'genus_tax_id': 434644,
  'is_vertebrate': False},
 'Limnodynastes ornatus': {'species_tax_name': 'Platyplectrum ornatum',
  'species_tax_id': 2741728,
  'genus_tax_name': 'Platyplectrum',
  'genus_tax_id': 2741727,
  'is_vertebrate': True},
 'Scalopus aquaticus': {'species_tax_name': 'Scalopus aquaticus',
  'species_tax_id': 71119,
  'genus_tax_name': 'Scalopus',
  'genus_tax_id': 71118,
  'is_vertebrate': True},
 'Rosellinia necatrix': {'species_tax_name': 'Rosellinia necatrix',
  'species_tax_id': 77044,
  'genus_tax_name': 'Rosellinia',
  'genus_tax_id': 77043,
  'is_vertebrate': False},
 'Perca fluviatilis': {'species_tax_name': 'Perca fluviatilis',
  'species_tax_id': 8168,
  'genus_tax_name': 'Perca',
  'genus_tax_id': 8166,
  'is_vertebrate': True},
 'Homo sapiens': {'species_tax_name': 'Homo sapiens',
  'species_tax_id': 9606,
  'genus_tax_name': 'Homo',
  'genus_tax_id': 9605,
  'is_vertebrate': True},
 'Sida sp.': {'species_tax_name': 'Sida sp. (in: eudicots)',
  'species_tax_id': 3408420,
  'genus_tax_name': 'Sida',
  'genus_tax_id': 108335,
  'is_vertebrate': False},
 'Diptera': {'is_vertebrate': False},
 'Drosophila ananassae': {'species_tax_name': 'Drosophila ananassae',
  'species_tax_id': 7217,
  'genus_tax_name': 'Drosophila',
  'genus_tax_id': 7215,
  'is_vertebrate': False},
 'Gallus gallus': {'species_tax_name': 'Gallus gallus',
  'species_tax_id': 9031,
  'genus_tax_name': 'Gallus',
  'genus_tax_id': 9030,
  'is_vertebrate': True}}

In [46]:
!datasets summary taxonomy taxon "Diptera"

{"reports": [{"query":["Diptera"],"taxonomy":{"children":[333826,265461,7148,7203],"classification":{"class":{"id":50557,"name":"Insecta"},"domain":{"id":2759,"name":"Eukaryota"},"kingdom":{"id":33208,"name":"Metazoa"},"order":{"id":7147,"name":"Diptera"},"phylum":{"id":6656,"name":"Arthropoda"}},"counts":[{"count":1974,"type":"COUNT_TYPE_ASSEMBLY"},{"count":1793695,"type":"COUNT_TYPE_GENE"},{"count":57805,"type":"COUNT_TYPE_tRNA"},{"count":34722,"type":"COUNT_TYPE_rRNA"},{"count":4975,"type":"COUNT_TYPE_snRNA"},{"count":4945,"type":"COUNT_TYPE_snoRNA"},{"count":1523099,"type":"COUNT_TYPE_PROTEIN_CODING"},{"count":20,"type":"COUNT_TYPE_miscRNA"},{"count":118750,"type":"COUNT_TYPE_ncRNA"},{"count":5,"type":"COUNT_TYPE_OTHER"}],"curator_common_name":"flies","current_scientific_name":{"name":"Diptera"},"current_scientific_name_is_formal":true,"genomic_moltype":"dsDNA","group_name":"flies","parents":[1,131567,2759,33154,33208,6072,33213,33317,1206794,88770,6656,197563,197562,3701028,3701030,6960,50557,85512,7496,33340,3701061,33392,3701062,3701063],"rank":"ORDER","tax_id":7147}}],"total_count": 1}