In [1]:
import pandas as pd
import os
import numpy as np
import math
import pytaxonkit
import subprocess
import json

In [50]:
!datasets download virus genome accession "AF538689.1"  --include protein --filename "test-data.zip"

Downloading: test-data.zip    1.52kB 9.18MB/s
Downloading: test-data.zip    1.52kB 9.18MB/s
Downloading: test-data.zip    4.07kB valid data package
Validating package files [================================================] 100% 5/5

In [137]:
!datasets summary taxonomy taxon "Barley"

Error: The taxonomy name 'Barley' is not exact. Try using one of the suggested taxids:
Barley yellow dwarf virus (species, taxid: 12037, viruses)
Barley stripe mosaic virus (no-rank, taxid: 12327, viruses)
Barley yellow dwarf virus-PAV (no-rank, taxid: 2169986, viruses)
Barley dwarf virus (no-rank, taxid: 497862, viruses)
Barley yellow dwarf virus MAV (no-rank, taxid: 2169984, viruses)
Barley virus G (no-rank, taxid: 1825924, viruses)
Cytorhabdovirus hordei (no-rank, taxid: 1985699, Barley yellow striate mosaic virus)
Barley yellow dwarf virus-PAS (no-rank, taxid: 2169985, viruses)
Barley yellow mosaic virus (no-rank, taxid: 12465, viruses)
Barley mild mosaic virus (no-rank, taxid: 12466, viruses)

Use datasets summary taxonomy taxon <command> --help for detailed help about a command.

In [2]:
dataset_csv_filepath = os.path.join(os.getcwd(), "..", "..", "..","..", "..", "input/data/bvbrc/BVBRC_reference_genome_20260429.csv")
df = pd.read_csv(dataset_csv_filepath, low_memory=False)
print(f"Dataset size: {df.shape}")
df.columns

Dataset size: (15731, 90)

Index(['Genome ID', 'Genome Name', 'Other Names', 'NCBI Taxon ID',
       'Taxon Lineage IDs', 'Taxon Lineage Names', 'Superkingdom', 'Kingdom',
       'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species',
       'Genome Status', 'Strain', 'Serovar', 'Biovar', 'Pathovar', 'MLST',
       'Segment', 'Subtype', 'H_type', 'N_type', 'H1 Clade Global',
       'H1 Clade US', 'H5 Clade', 'pH1N1-like', 'Lineage', 'Clade', 'Subclade',
       'Other Typing', 'Culture Collection', 'Type Strain', 'Reference',
       'Genome Quality', 'Completion Date', 'Publication', 'Authors',
       'BioProject Accession', 'BioSample Accession', 'Assembly Accession',
       'SRA Accession', 'GenBank Accessions', 'Sequencing Center',
       'Sequencing Status', 'Sequencing Platform', 'Sequencing Depth',
       'Assembly Method', 'Chromosome', 'Plasmids', 'Contigs', 'Size',
       'GC Content', 'Contig L50', 'Contig N50', 'TRNA', 'RRNA', 'Mat Peptide',
       'CDS', 'Coarse Consistency', 'Fine Consistency', 'CheckM Contamination',
       'CheckM Completeness', 'Genome Quality Flags', 'Isolation Source',
       'Isolation Comments', 'Collection Date', 'Collection Year', 'Season',
       'Isolation Country', 'State/Province', 'County', 'City',
       'Geographic Group', 'Geographic Location', 'Other Environmental',
       'Host Name', 'Host Common Name', 'Host Sex', 'Host Age', 'Host Health',
       'Host Group', 'Lab Host', 'Passage', 'Other Clinical',
       'Additional Metadata', 'Comments', 'Date Inserted', 'Date Modified'],
      dtype='object')

In [3]:
df

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,...,Host Age,Host Health,Host Group,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified
0,1000373.10,Rosellinia necatrix quadrivirus 1 W1118,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-06T11:05:04.123Z,2025-12-06T11:05:04.123Z
1,1000373.40,Rosellinia necatrix quadrivirus 1 W1075,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-06T08:01:47.037Z,2025-12-06T08:01:47.037Z
2,1000373.50,Rosellinia necatrix quadrivirus 1 W1075,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-06T08:01:47.164Z,2025-12-06T08:01:47.164Z
3,1000411.30,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:04:18.329Z,2021-01-23T22:04:18.329Z
4,1000411.40,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Nonhuman Mammal,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:06:18.856Z,2021-01-23T22:06:18.856Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15726,999729.23,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:40:21.986Z,2022-03-12T21:40:21.986Z
15727,999729.24,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:34:20.054Z,2022-03-12T21:34:20.054Z
15728,999729.25,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:49:25.104Z,2022-03-12T21:49:25.104Z
15729,999729.35,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,Insect,NaN,NaN,NaN,NaN,NaN,2022-05-01T01:51:20.496Z,2022-05-01T01:51:20.496Z
15730,999883.50,Lausannevirus 7715,NaN,999883,10239;2732004;2732005;2732007;2732523;2732555;...,Viruses;Varidnaviria;Bamfordvirae;Nucleocytovi...,Viruses,Bamfordvirae,Nucleocytoviricota,Megaviricetes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-12-16T15:15:58.376Z,2025-12-16T15:15:58.376Z

In [4]:
df["Host Group"].value_counts()

Nonhuman Mammal    1395
Bacteria            882
Plant               779
Insect              770
Human               610
Avian               371
Tick                298
Lab                  79
Fish                 71
Reptile              35
Sea Mammal           25
Crustaceans          20
Amphibian             2
Fungi                 1
Name: Host Group, dtype: int64

In [5]:
df["Host Name"].nunique()

3771

In [26]:
df[df["Host Name"].isna()][["Genome Name", "GenBank Accessions"]]

                               Genome Name GenBank Accessions
33                     Ljungan virus M1146           AF538689
35             Bos taurus papillomavirus 7           DQ217793
45               Simian sapelovirus 1 2383          NC_004451
46               Simian sapelovirus 1 2383           AY064708
47               Porcine sapelovirus 1 V13           AF406813
...                                    ...                ...
15631  Plutella xylostella granulovirus K1           AF270937
15633              Pseudomonas phage phi15           FR823298
15634              Tanapox virus TPV-Kenya           EF420156
15672      Titi monkey adenovirus ECC-2011           HQ913600
15673      Titi monkey adenovirus ECC-2011          NC_020487

[4349 rows x 2 columns]

In [7]:
print(df["Host Name"].nunique())
print(df["Host Common Name"].nunique())

3771
369

In [10]:
print(sum(df["Host Name"].isna()))
print(sum(df["Host Common Name"].isna()))
print(sum(df["Host Name"].isna() & ~df["Host Common Name"].isna() ))

4349
10393
34

In [6]:
df[df["Host Name"].isna() & ~df["Host Common Name"].isna()][["Genome ID", "GenBank Accessions", "Host Name", "Host Common Name"]]

          Genome ID GenBank Accessions Host Name Host Common Name
125    1.024541e+04          NC_006998       NaN         Lab host
126    1.025430e+04           AY243312       NaN         Lab host
519    1.078429e+04          NC_001540       NaN         Lab host
520    1.078829e+04          NC_001539       NaN         Lab host
521    1.079439e+04          NC_001510       NaN         Lab host
522    1.079440e+04             J02275       NaN         Lab host
951    1.133292e+06           JN939331       NaN         Lab host
952    1.133294e+06           JN939332       NaN         Lab host
1189   1.168745e+06           JQ797329       NaN         Lab host
2082   1.327970e+06           KC821606       NaN         Lab host
2083   1.327971e+06           KC821607       NaN         Lab host
2084   1.327972e+06           KC821608       NaN         Lab host
2085   1.327973e+06           KC821609       NaN         Lab host
2086   1.327977e+06           KC821613       NaN         Lab host
2087   1.327978e+06           KC821614       NaN         Lab host
2088   1.327981e+06           KC821617       NaN         Lab host
2089   1.327982e+06           KC821618       NaN         Lab host
2090   1.327983e+06           KC821619       NaN         Lab host
2091   1.327984e+06           KC821620       NaN         Lab host
2092   1.327986e+06           KC821622       NaN         Lab host
2093   1.327988e+06           KC821623       NaN         Lab host
2094   1.327991e+06           KC821624       NaN         Lab host
2095   1.328030e+06           KC821632       NaN         Lab host
2096   1.328031e+06           KC821633       NaN         Lab host
5729   1.972567e+06           JF911700       NaN         Lab host
5730   1.972568e+06          NC_025378       NaN         Lab host
8879   2.526028e+05          NC_006148       NaN         Lab host
13607  4.369115e+05          NC_011050       NaN         Lab host
14315  5.850604e+05           HB426768       NaN           Patent
14316  5.850613e+05           HC084988       NaN           Patent
14317  5.850634e+05           HC085020       NaN           Patent
14319  5.850653e+05           HC000816       NaN           Patent
14320  5.850684e+05           HC000847       NaN           Patent
14321  5.850743e+05           HC000785       NaN           Patent

In [15]:
sum(~df["Host Name"].isna())

11382

In [7]:
df = df[~df["Host Name"].isna()]
df.shape

(11382, 90)

In [88]:
!datasets summary taxonomy taxon "Homo sapiens, Sus scrofa"

{"reports": [{"query":["Homo sapiens"],"taxonomy":{"children":[741158,63221],"classification":{"class":{"id":40674,"name":"Mammalia"},"domain":{"id":2759,"name":"Eukaryota"},"family":{"id":9604,"name":"Hominidae"},"genus":{"id":9605,"name":"Homo"},"kingdom":{"id":33208,"name":"Metazoa"},"order":{"id":9443,"name":"Primates"},"phylum":{"id":7711,"name":"Chordata"},"species":{"id":9606,"name":"Homo sapiens"}},"counts":[{"count":2497,"type":"COUNT_TYPE_ASSEMBLY"},{"count":193866,"type":"COUNT_TYPE_GENE"},{"count":701,"type":"COUNT_TYPE_tRNA"},{"count":785,"type":"COUNT_TYPE_rRNA"},{"count":168,"type":"COUNT_TYPE_snRNA"},{"count":4,"type":"COUNT_TYPE_scRNA"},{"count":1201,"type":"COUNT_TYPE_snoRNA"},{"count":20624,"type":"COUNT_TYPE_PROTEIN_CODING"},{"count":22583,"type":"COUNT_TYPE_ncRNA"},{"count":128261,"type":"COUNT_TYPE_BIOLOGICAL_REGION"},{"count":843,"type":"COUNT_TYPE_OTHER"}],"curator_common_name":"human","current_scientific_name":{"authority":"Linnaeus, 1758","name":"Homo sapiens"},"current_scientific_name_is_formal":true,"genomic_moltype":"dsDNA","group_name":"primates","parents":[1,131567,2759,33154,33208,6072,33213,33511,7711,89593,7742,7776,117570,117571,8287,1338369,32523,32524,40674,32525,9347,1437010,314146,9443,376913,314293,9526,314295,9604,207598,9605],"rank":"SPECIES","tax_id":9606}},{"query":[" Sus scrofa"],"taxonomy":{"children":[2485929,490583,310261,415978,375579,309914,1611878,1611880,1611879,375578,1017268,9825,309913,291050,310260,1170810],"classification":{"class":{"id":40674,"name":"Mammalia"},"domain":{"id":2759,"name":"Eukaryota"},"family":{"id":9821,"name":"Suidae"},"genus":{"id":9822,"name":"Sus"},"kingdom":{"id":33208,"name":"Metazoa"},"order":{"id":91561,"name":"Artiodactyla"},"phylum":{"id":7711,"name":"Chordata"},"species":{"id":9823,"name":"Sus scrofa"}},"counts":[{"count":54,"type":"COUNT_TYPE_ASSEMBLY"},{"count":45429,"type":"COUNT_TYPE_GENE"},{"count":554,"type":"COUNT_TYPE_tRNA"},{"count":6,"type":"COUNT_TYPE_rRNA"},{"count":20833,"type":"COUNT_TYPE_PROTEIN_CODING"},{"count":6022,"type":"COUNT_TYPE_ncRNA"},{"count":141,"type":"COUNT_TYPE_OTHER"}],"curator_common_name":"pig","current_scientific_name":{"authority":"Linnaeus, 1758","name":"Sus scrofa"},"current_scientific_name_is_formal":true,"genomic_moltype":"dsDNA","group_name":"even-toed ungulates \u0026 whales","has_type_material":true,"parents":[1,131567,2759,33154,33208,6072,33213,33511,7711,89593,7742,7776,117570,117571,8287,1338369,32523,32524,40674,32525,9347,1437010,314145,91561,35497,9821,9822],"rank":"SPECIES","tax_id":9823}}],"total_count": 2}

In [140]:
VERTEBRATA_TAX_ID = 7742

def get_host_metadata(host_names):
    host_metadata = {}
    error_hosts = []
    n = len(host_names)
    for i, host_name in enumerate(host_names):
        print(f"({i}) {host_name}")
        try: 
            output = subprocess.run(["datasets", "summary", "taxonomy", "taxon", host_name], capture_output=True)
            #tax_json = json.loads(output.stdout)["reports"][0]["taxonomy"]["classification"]
            output_json = json.loads(output.stdout)
            reports = output_json["reports"]
            report_count = int(output_json["total_count"])
            for report in reports:
                tax_json = report["taxonomy"]
                classification_json = tax_json["classification"]
                metadata = {}
                if "species" in classification_json:
                    metadata["species_tax_name"] = classification_json["species"]["name"]
                    metadata["species_tax_id"] = classification_json["species"]["id"]
    
                if "genus" in classification_json:
                    metadata["genus_tax_name"] = classification_json["genus"]["name"]
                    metadata["genus_tax_id"] = classification_json["genus"]["id"]
    
                if "family" in tax_json:
                    metadata["family_tax_name"] = classification_json["family"]["name"]
                    metadata["family_tax_id"] = classification_json["family"]["id"]
    
                parents = tax_json["parents"]
                if VERTEBRATA_TAX_ID in parents:
                    metadata["is_vertebrate"] = True
                else:
                    metadata["is_vertebrate"] = False
                    
                host_metadata[host_name] = metadata
        except Exception as e:
            error_hosts.append(host_name)
            print(e)
    return host_metadata, error_hosts

In [78]:
df["host_name_cleaned"] = df["Host Name"].apply(lambda x: " ".join(x.split(" ")[:2]))

/tmp/ipykernel_1450585/3428461402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["host_name_cleaned"] = df["Host Name"].apply(lambda x: " ".join(x.split(" ")[:2]))

In [79]:
df["Host Name"].nunique()

3771

In [80]:
df["Host Name"].value_counts()

Homo sapiens                           577
Mycobacterium smegmatis mc2 155        172
Escherichia coli                       131
Klebsiella pneumoniae                  118
Pseudomonas aeruginosa                  85
                                      ...
Salmo salar l. (atlantic salmon)         1
Cicer arietinum voucher dar 76857        1
Cicer arietinum voucher brip 52877a      1
Cicer arietinum voucher brip 52878a      1
Digitaria didactyla willd                1
Name: Host Name, Length: 3771, dtype: int64

In [142]:
df["host_name_cleaned"].nunique()

2635

In [143]:
df["host_name_cleaned"].value_counts()

Homo sapiens               579
Escherichia coli           302
Mycobacterium smegmatis    183
Klebsiella pneumoniae      174
Pseudomonas aeruginosa     143
                          ...
Feral pigeon                 1
Cercopithecus mitis          1
Datura inoxia                1
Ictalurus punctatus          1
Rhododendron maximum         1
Name: host_name_cleaned, Length: 2635, dtype: int64

In [144]:
hosts = df["host_name_cleaned"].unique()

In [106]:
for i, host in enumerate(hosts):
    if host == "Lycopersicon esculentum":
        break

print(i)
hosts[143]

143

'Lycopersicon esculentum'

In [145]:
host_metadata, error_hosts = get_host_metadata(hosts)

(0) Rosellinia necatrix
(1) Rodent
Expecting value: line 1 column 1 (char 0)
(2) Sandfly
Expecting value: line 1 column 1 (char 0)
(3) Homo sapiens
(4) mosquito
Expecting value: line 1 column 1 (char 0)
(5) Chilli
Expecting value: line 1 column 1 (char 0)
(6) Scalopus aquaticus
(7) Vernonia cinerea
(8) Perca fluviatilis
(9) Limnodynastes ornatus
(10) Gallus gallus
(11) Drosophila ananassae
(12) Diptera
(13) Sida sp.
(14) Shigella flexneri
(15) Hardenbergia comptoniana
(16) Spissistilus festinus
(17) Lutzomyia sp.
(18) Staphylococcus aureus
(19) Ipomoea batatas
(20) Ipomoea purpurea
(21) Ipomoea indica
(22) Rhodococcus equi
(23) Trichomonas vaginalis
(24) Triticum aestivum
(25) Ixodes (Trichotoixodes)
Expecting value: line 1 column 1 (char 0)
(26) Uria sp.
Expecting value: line 1 column 1 (char 0)
(27) Musa sp.
(28) Euphorbia heterophylla
(29) cutthroat trout
(30) Thysanoplusia orichalcea
(31) raccoon
(32) Columba livia
(33) sheep
(34) Solanum lycopersicum
(35) Stenotrophomonas maltophilia
(36) Jatropha curcas
(37) ring-necked pheasant
Expecting value: line 1 column 1 (char 0)
(38) wild bird
Expecting value: line 1 column 1 (char 0)
(39) Choristoneura biennis
(40) Bos taurus
(41) Erwinia amylovora
(42) Eragrostis minor
(43) Cercopithecus aethiops
Expecting value: line 1 column 1 (char 0)
(44) Clostridium difficile
(45) Passiflora incarnata
(46) Aeropyrum pernix
(47) Chenopodium ambrosioides
(48) Macaca mulatta
(49) Macaca silenus
(50) Macaca nemestrina
(51) Equus caballus
(52) Mycobacterium smegmatis
(53) Physalis pubescens
(54) Flavobacterium columnare
(55) Fig
Expecting value: line 1 column 1 (char 0)
(56) Sus scrofa
(57) Mosquito
Expecting value: line 1 column 1 (char 0)
(58) Ophicephalus struatus
Expecting value: line 1 column 1 (char 0)
(59) Carica papaya
(60) Mus musculus
(61) Apodemus sylvaticus
(62) Rattus norvegicus
(63) Tuber aestivum
(64) Datura inoxia
(65) Ovis aries
(66) Ictalurus punctatus
(67) Gorilla
(68) gibbon
(69) Cultivated blackberry
Expecting value: line 1 column 1 (char 0)
(70) Anatid species
Expecting value: line 1 column 1 (char 0)
(71) Spodoptera exigua
(72) Spodoptera littoralis
(73) Helicoverpa armigera
(74) Operophtera brumata
(75) Lilium martagon
(76) Elettaria cardamomum
(77) Agrotis segetum
(78) Potato
(79) Brassica napus
(80) Sida rhomboidea
(81) Blainvillea rhomboidea
(82) Asystasia
(83) Asystasia gangetica
(84) Kinnow mandarin
Expecting value: line 1 column 1 (char 0)
(85) Escherichia coli
(86) Ageratum conyzoides
(87) sentinel hamster
Expecting value: line 1 column 1 (char 0)
(88) Acinetobacter baumannii
(89) Frog
Expecting value: line 1 column 1 (char 0)
(90) Rana pipiens
(91) domestic pig
(92) Ornithodoros sp.
(93) Ornithodoros porcinus
(94) Tick
Expecting value: line 1 column 1 (char 0)
(95) warthog
Expecting value: line 1 column 1 (char 0)
(96) Grapevine (chardonel)
Expecting value: line 1 column 1 (char 0)
(97) Chlorella variabilis
(98) Marmota caudata
(99) Salmonella enterica
(100) Phlebotominae sp.
(101) Mastomys natalensis
(102) Micromys minutus
(103) Solanum tuberosum
(104) Common marmoset
Expecting value: line 1 column 1 (char 0)
(105) Vibrio cholerae
(106) Streptomyces venezuelae
(107) Hyposidra talaca
(108) dog
(109) Bacillus subtilis
(110) Myotis nattererii
(111) Lygus lineolaris
(112) Paspalum dilatatum
(113) Streptomyces albus;
Expecting value: line 1 column 1 (char 0)
(114) Nicotiana edwardsonii
(115) Enterococcus faecalis
(116) Peromyscus maniculatus
(117) Peromyscus crinitus
(118) Microtus pennsylvanicus
(119) Sclerotinia sclerotiorum
(120) Streptococcus pneumoniae
(121) Miniopterus pusillus
(122) Miniopterus magnater
(123) Rhinolophus sinicus
(124) Duranta repens
(125) Dahlia variabilis
(126) Glycine max
(127) Cynanchum wilfordii
(128) Salmonella sp.
(129) Morelia spilota
(130) Canis lupus
(131) Cassava
(132) Tamus communis
(133) Urochloa maxima
(134) Digitaria ciliaris
(135) Digitaria sp.
Expecting value: line 1 column 1 (char 0)
(136) Eustachys petraea
(137) Pennisetum sp.
(138) Setaria barbata
(139) Panicum maximum
(140) Brachiaria deflexa
(141) Urochloa plantaginea
(142) Tomato
(143) Lycopersicon esculentum
(144) Hordeum vulgare
(145) Barley
Expecting value: line 1 column 1 (char 0)
(146) Triticum
(147) Cenchrus myosuroides
(148) Macroptilium lathyroides
(149) Pepper
Expecting value: line 1 column 1 (char 0)
(150) Chile pepper
Expecting value: line 1 column 1 (char 0)
(151) Beta vulgaris
(152) Capsicum annuum
(153) pig
(154) Canine
Expecting value: line 1 column 1 (char 0)
(155) Pseudomonas aeruginosa
(156) Coturnix coturnix
(157) Ochlerotatus taeniorhynchus
(158) Mirabilis jalapa
(159) Sida rhombifolia
(160) Human
(161) maize
(162) Zea mays
(163) rice
Expecting value: line 1 column 1 (char 0)
(164) Rice
Expecting value: line 1 column 1 (char 0)
(165) Oryza sativa
(166) Diachasmimorpha longicaudata
(167) Pseudomonas tolaasii
(168) Gordonia terrae
(169) Aedes vittatus
(170) horse
(171) Buteo jamaicensis
(172) Bhk-21
Expecting value: line 1 column 1 (char 0)
(173) Culex sp.
(174) Yersinia enterocolitica
(175) Bacteroides fragilis
(176) Rhodobacter capsulatus
(177) Bombyx mori
(178) Felis catus
(179) Salmonella typhimurium
(180) white stork
(181) Gordonia rubropertincta
(182) Nocardia brasiliensis
(183) Rhodococcus erythropolis
(184) Rhodococcus rhodochrous
(185) Shigella sonnei
(186) chicken
(187) Embryonated chicken
Expecting value: line 1 column 1 (char 0)
(188) Epomophorus sp.
Expecting value: line 1 column 1 (char 0)
(189) Eidolon helvum
(190) Pseudomonas putida
(191) Diaporthe ambigua
(192) turkey
(193) Pectobacterium atrosepticum
(194) Sikkim rat
Expecting value: line 1 column 1 (char 0)
(195) Bacillus cereus/thuringiensis
Expecting value: line 1 column 1 (char 0)
(196) Trichosurus vulpecula
(197) Neodiprion sertifer
(198) Dichopogon strictus
(199) Hylocereus undatus
(200) Aporocactus flagelliformis
(201) Pan troglodytes
(202) Phoca vitulina
(203) cattle, wild
(204) Apium graveolens
(205) Bacillus thuringiensis
(206) pathenogenic Salmonella
Expecting value: line 1 column 1 (char 0)
(207) Manihot esculenta
(208) Bacillus cereus
(209) Philander opossum
(210) Bovine
Expecting value: line 1 column 1 (char 0)
(211) Aeromonas salmonicida
(212) Pectobacterium carotovorum
(213) equine
Expecting value: line 1 column 1 (char 0)
(214) Tomato plant
Expecting value: line 1 column 1 (char 0)
(215) Clostridium perfringens
(216) Psittacula krameri
(217) Platycercus elegans
(218) Clitoria ternatea
(219) Martes martes
(220) Helicoverpa zea
(221) Oncorhynchus tschawytscha
(222) Centrosema brasilianum
(223) Macroptilium sp.
Expecting value: line 1 column 1 (char 0)
(224) Klebsiella pneumoniae
(225) Xanthomonas vesicatoria
(226) Valsa ceratosperma
(227) Sauropus androgynus
(228) Erwinia pyrifoliae
(229) Artibeus jamaicensis
(230) Persea americana
(231) Burkholderia cenocepacia
(232) Phytophthora infestans
(233) Spodoptera frugiperda
(234) Artemisia annua
(235) Mus minutoides
(236) Synechococcus sp.
(237) Cronobacter sakazakii
(238) Escherichia sp.
(239) Hibiscus rosa-sinensis
(240) Trichechus manatus
(241) Tursiops truncatus
(242) Zygodontomys brevicauda
(243) Myotis macrodactylus
(244) Klebsiella sp.
(245) Enterobacter cloacae
(246) Natrialba magadii
(247) Zygosaccharomyces bailii
(248) Coriandrum sativum
(249) Malvastrum coromandelianum
(250) Sidastrum micranthum
(251) Vibrio parahaemolyticus
(252) Enterobacter cancerogenus
(253) Ralstonia solanacearum
(254) Vibrio alginolyticus
(255) Haloarcula hispanica
(256) Helicobacter pylori
(257) Halorubrum sp.
(258) Halogeometricum sp.
(259) asymptomatic piglets
Expecting value: line 1 column 1 (char 0)
(260) Atlantic salmon
(261) Ameiva ameiva
(262) Ixodes redikorzevi
(263) common moorhen
(264) magpie-robin
Expecting value: line 1 column 1 (char 0)
(265) night-heron
Expecting value: line 1 column 1 (char 0)
(266) sparrow
Expecting value: line 1 column 1 (char 0)
(267) white-eye
Expecting value: line 1 column 1 (char 0)
(268) wigeon
Expecting value: line 1 column 1 (char 0)
(269) Vibrio natriegens
(270) Oryctolagus cuniculus
(271) Sponge gourd
Expecting value: line 1 column 1 (char 0)
(272) Vibrio vulnificus
(273) Leuconostoc mesenteroides
(274) Agrobacterium sp.
(275) Salinivibrio costicola
(276) Enterococcus faecium
(277) Clitocybe odora
(278) Cicer arietinum
(279) Equus asinus
(280) Rupicapra rupicapra
(281) Vulpes vulpes
(282) Macaca fascicularis
(283) Civettictis civetta
(284) Persicivirga sp.
Expecting value: line 1 column 1 (char 0)
(285) Vinca rosea
(286) Soybean
(287) swine
Expecting value: line 1 column 1 (char 0)
(288) Listeria monocytogenes
(289) Wheat
Expecting value: line 1 column 1 (char 0)
(290) Rusa alfredi
(291) Tobacco
Expecting value: line 1 column 1 (char 0)
(292) Hylocereus sp.
(293) Pteropus poliocephalus
(294) bat
Expecting value: line 1 column 1 (char 0)
(295) Xanthomonas citri
(296) Sida spp.
Expecting value: line 1 column 1 (char 0)
(297) Giraffa camelopardalis
(298) goose embryo
Expecting value: line 1 column 1 (char 0)
(299) Dog
(300) Aspidites melanocephalus
(301) Miniopterus schreibersii
(302) Myotis myotis
(303) Myotis ricketti
(304) Canis familiaris
(305) Celeribacter sp.
(306) Aeromonas sp.
(307) Premna serratifolia
(308) Caladenia latifolia
(309) Jacquemontia pentantha
(310) Phaseolus vulgaris
(311) Abelmoschus esculentus
(312) Citrus sp.
(313) Ixodes uriae
(314) Aeromonas hydrophila
(315) Streptomyces hygroscopicus
(316) Bacillus pumilus
(317) Caulobacter crescentus
(318) Pseudomonas fluorescens
(319) Horse
(320) Yersinia pestis
(321) Vaccinium corymbosum
(322) Chrysodeixis includens
(323) woodchuck
(324) Streptomyces sp.
(325) Salmonella enteritidis
(326) Diospyros kaki
(327) Mustela putorius
(328) Rose cv.
Expecting value: line 1 column 1 (char 0)
(329) Rhipicephalus decoloratus
(330) Eureka lemon
Expecting value: line 1 column 1 (char 0)
(331) Desmodus rotundus
(332) Rhinolophus ferrumequinum
(333) Chrysanthemum
(334) Zalophus californianus
(335) French bean
Expecting value: line 1 column 1 (char 0)
(336) Amblyomma americanum
(337) Cowpea
Expecting value: line 1 column 1 (char 0)
(338) Phytolacca americana
(339) Rhizobium etli
(340) Luffa cylindrica
Expecting value: line 1 column 1 (char 0)
(341) Prunus domestica
(342) Prunus cerasus
(343) Prunus sp.
(344) Pteropus sp.
(345) Vitis sp.
(346) Potato (solanum
Expecting value: line 1 column 1 (char 0)
(347) Maize
(348) Lepomis macrochirus
(349) Corallus annulatus
(350) Boa constrictor
(351) Pouzolzia zeylanica
(352) Lactobacillus plantarum
(353) Listeria sp.
(354) Dalechampia sp.
(355) Datura stramonium
(356) goose
(357) Mansonia uniformis
(358) Lactococcus lactis
(359) Campylobacter jejuni
(360) Acinetobacter soli
(361) Propionibacterium acnes
(362) Culex nebulosus
(363) Anopheles coustani
(364) Pantala flavescens
(365) Erythemis simplicicollis
(366) Erythrodiplax umbrata
(367) Miathyria marcella
(368) Tramea lacerata
(369) Equus ferus
(370) Providencia stuartii
(371) Ateles paniscus
(372) Cebus albifrons
(373) Cercopithecus erythrotis
(374) Piliocolobus rufomitratus
(375) Saimiri sciureus
(376) Vigna unguiculata
(377) Culex tritaeniorhynchus
(378) Streptomyces coelicolor
(379) Turkey
(380) Brugmansia suaveolens
(381) Swine
Expecting value: line 1 column 1 (char 0)
(382) Sheep
(383) Haliotis rubra
(384) Spodoptera exempta
(385) Allium sativum
(386) Rubus canadensis
(387) Anopheles vagus
(388) Ochlerotatus caspius
(389) Rhesus monkey
(390) Garlic
(391) Blechum pyramidatum
(392) Medicago sativa
(393) Solanum nodiflorum
(394) Diuris pedunculata
(395) Trifolium subterraneum
(396) Nicotiana velutina
(397) Amoeba
(398) Erythrodiplax fusca
(399) Vitis vinifera
(400) Percidae
(401) Pigeon
Expecting value: line 1 column 1 (char 0)
(402) Saccharum hybrid
(403) Papaver somniferum
(404) rat
Expecting value: line 1 column 1 (char 0)
(405) Staphylococcus xylosus
(406) Serratia sp.
Expecting value: line 1 column 1 (char 0)
(407) Leuconostoc pseudomesenteroides
(408) Vibrio harveyi
(409) Sida ciliaris
(410) Rhizoctonia solani
(411) Mulberry
Expecting value: line 1 column 1 (char 0)
(412) Sida micrantha
(413) Sida urens
(414) Arachis hypogaea
(415) Nilaparvata lugens
(416) Stenocephalemys albipes
(417) Acanthamoeba polyphaga
(418) Xanthomonas campestris
(419) Culex tarsalis
(420) Culicinae sp.
(421) Culex dunni
(422) Riparia paludicola
(423) Bird(sylvia curraca)
Expecting value: line 1 column 1 (char 0)
(424) Culicoides insignis
(425) Sabethes intermedius
(426) Trichoprosopon theobaldi
(427) Alcea rosea
(428) Chaerephon sp.
(429) Dahlia pinnata
(430) Synechococcus
(431) Nyctalus velutinus
(432) Cyanoramphus auriceps
(433) Burkholderia pseudomallei
(434) Candidatus Pelagibacter
(435) Fusarium graminearum
(436) Nile crocodile
(437) Papio cynocephalus
(438) Dioscorea opposita
(439) Tinca tinca
(440) Ctenopharyngodon idella
(441) Chaetoceros setoensis
(442) Meleagris gallopavo
(443) Choristoneura rosaceana
(444) Adoxophyes honmai
(445) Mythimna separata
(446) Botrytis cinerea
(447) suckling newborn
Expecting value: line 1 column 1 (char 0)
(448) Brevibacillus laterosporus
(449) Helianthus annuus
(450) Corchorus olitorius
(451) Scheffersomyces segobiensis
(452) Miniopterus griveaudi
(453) Hipposideros armiger
(454) Psittacus erithacus
(455) Coquillettidia xanthogaster
(456) Sporobolus sp.
Expecting value: line 1 column 1 (char 0)
(457) Solanum licopersicum
Expecting value: line 1 column 1 (char 0)
(458) Hipposideros pomona
(459) Mycobacterium avium
(460) Saguinus labiatus
(461) Pteropus giganteus
(462) Sweet potato
(463) Drosophila affinis
(464) Bacillus anthracis
(465) Bacillus weihenstephanensis
(466) Capraria biflora
(467) Prunus avium
(468) Abutilon permolle
(469) Vigna elegans
(470) Lonicera japonica
(471) hybrid snakehead
Expecting value: line 1 column 1 (char 0)
(472) Pseudoalteromonas marina
(473) Allamanda cathartica
(474) Diospyros virginiana
(475) Neotoma lepida
(476) Medicago lupulina
(477) Trifolium pratense
(478) Trifolium repens
(479) Trifolium incarnatum
(480) Anethum graveolens
(481) Habenaria radiata
(482) Kalanchoe blossfeldiana
(483) Edwardsiella ictaluri
(484) Otomops martiensseni
(485) Flavobacterium psychrophilum
(486) Streptomyces lividans
(487) Pig
(488) Eptesicus fuscus
(489) Aselliscus stoliczkanus
(490) Rhinolophus hipposideros
(491) Vespertilio sinensis
(492) Pipistrellus sp.
(493) Culex vishnui
(494) Paenibacillus larvae
(495) Talpa europaea
(496) Staphylococcus epidermidis
(497) Rousettus aegyptiacus
(498) Mycobacterium smegamtis
Expecting value: line 1 column 1 (char 0)
(499) Capsicum
(500) Capsicum sp.
(501) Lonomia obliqua
(502) Peridroma sp.
(503) Pekin duck
(504) Sand fly
Expecting value: line 1 column 1 (char 0)
(505) Castor canadensis
(506) Paspalum setaceum
(507) black-and-white colobus
Expecting value: line 1 column 1 (char 0)
(508) Sinorhizobium meliloti
(509) Proteus mirabilis
(510) Pseudoalteromonas sp.
(511) Microcystis aeruginosa
(512) Anabaena variabilis
(513) Prunus armeniaca
(514) Hemileuca sp.
(515) Rangifer tarandus
(516) Macropodidae
(517) feline
Expecting value: line 1 column 1 (char 0)
(518) Hipposideros gigas
(519) Blackberry
Expecting value: line 1 column 1 (char 0)
(520) Damaliscus lunatus
(521) Bacilluls thuringiensis
Expecting value: line 1 column 1 (char 0)
(522) Hemidesmus indicus
(523) Acrocephalus scirpaceus
(524) Myotis lucifugus
(525) Streptococcus thermophilus
(526) Erinaceus europaeus
(527) Rousettus leschenaultii
(528) Struthio camelus
(529) Petroica traversi
(530) Turdus merula
(531) Cracticus torquatus
(532) bird
Expecting value: line 1 column 1 (char 0)
(533) Gossypium hirsutum
(534) Anguilla anguilla
(535) Andrias davidianus
(536) Lisianthus
Expecting value: line 1 column 1 (char 0)
(537) Loxodonta africana
(538) Lactobacillus delbrueckii
(539) methicillin-resistant Staphylococcus
Expecting value: line 1 column 1 (char 0)
(540) pigeon
Expecting value: line 1 column 1 (char 0)
(541) Diuris longifolia
(542) Pimephales promelas
(543) Myotis davidii
(544) Anser sp.
(545) Pleione humilis
(546) cricket
Expecting value: line 1 column 1 (char 0)
(547) Anopheles annulipes
(548) Aedes vigilax
(549) Bacillus megaterium
(550) Clavibacter michiganensis
(551) Momordica charantia
(552) Parthenium hysterophorus
(553) Erwinia sp.
(554) Mesocricetus auratus
(555) Rhizoctonia cerealis
(556) whitetail deer
Expecting value: line 1 column 1 (char 0)
(557) Hipposideros commersoni
Expecting value: line 1 column 1 (char 0)
(558) Cronobacter turicensis
(559) Mont1 megavirus
Expecting value: line 1 column 1 (char 0)
(560) Plantain
Expecting value: line 1 column 1 (char 0)
(561) Arrhenatherum elatius
(562) pepper
Expecting value: line 1 column 1 (char 0)
(563) Solenopsis invicta;
Expecting value: line 1 column 1 (char 0)
(564) Lactobacillus paracasei
(565) Shigella boydii
(566) Arthrobacter sp.
(567) Xylella fastidiosa
(568) Achromobacter xylosoxidans
(569) Anthocercis littorea
(570) E. coli
Expecting value: line 1 column 1 (char 0)
(571) Enhydra lutris
(572) Aethomys medicatus
(573) Sigesbeckia glabrescens
(574) Anaxyrus boreas
(575) Penaeus vannamei
(576) Dioscorea rotundata
(577) Acanthamoeba sp.
(578) Bing cherry
Expecting value: line 1 column 1 (char 0)
(579) Ornithodoros coriaceus
(580) Serinus canaria
(581) Hedyotis uncinella
(582) Humulus lupulus
(583) Amblyomma (Theileriella)
Expecting value: line 1 column 1 (char 0)
(584) Methanobacterium formicicum
(585) avian pathogenic
Expecting value: line 1 column 1 (char 0)
(586) Spinach
(587) Enterococcus sp.
(588) Oenococcus oeni
(589) Cervus elaphus
(590) Delphinapterus leucas
(591) Cow
(592) Pisum sativum
(593) Bandicota sp.
(594) Cyprinus carpio
(595) Cebus apella
(596) Lens culinaris
(597) Shewanella putrefaciens
(598) Salmonella Typhimurium
(599) Oecomys bicolor
(600) black goat
Expecting value: line 1 column 1 (char 0)
(601) Nyctalus noctula
(602) Procordulia grayi
(603) Xanthocnemis zealandica
(604) Piliocolobus tephrosceles
(605) Synedrella nodiflora
(606) Citrobacter rodentium
(607) Astragalus sinicus
(608) Bdellovibrio bacteriovorus
(609) Ixodes lividus
(610) Culex portesi
(611) Ixodes eudyptidis
(612) Tasmanian tick
Expecting value: line 1 column 1 (char 0)
(613) Microbacterium oxydans
(614) Rhizobium gallicum
(615) Pseudomonas syringae
(616) Antheraea pernyi
(617) Elephas maximus
(618) Ustilaginoidea virens
(619) Lemniscomys striatus
(620) walrus
(621) Cucurbita pepo
(622) Luffa acutangula
(623) Atheris squamigera
(624) Lactobacillus rhamnosus
(625) Xanthomonas axonopodis
(626) Fulmarus glacialis
(627) Eptesicus serotinus
(628) Anopheles minimus
(629) Lagenaria siceraria
(630) Danaus plexippus
(631) Fulica atra
(632) Rattus rattus
(633) Aureococcus anophagefferens
(634) Mink
Expecting value: line 1 column 1 (char 0)
(635) Andrographis paniculata
(636) Axonopus compressus
(637) Red currant
(638) Musa spp.
Expecting value: line 1 column 1 (char 0)
(639) Dinoroseobacter shibae
(640) Dickeya sp.
(641) Ochlerotatus fulvus
(642) Pygoscelis adeliae
(643) Vibrio sp.
(644) Serratia marcescens
(645) Coracias garrulus
(646) Indotestudo forsteni
(647) Corvus corone
(648) Jatropha gossypiifolia
(649) Culex chidesteri
(650) Beauveria bassiana
(651) Lactococcus garvieae
(652) Phodopus sungorus
(653) Salmo salar
(654) Jacquemontia sp.
Expecting value: line 1 column 1 (char 0)
(655) TN10
Expecting value: line 1 column 1 (char 0)
(656) Leishmania aethiopica
(657) Apodemus peninsulae
(658) Haptolina ericina
(659) Prymnesium kappa
(660) Culex modestus
(661) Plumeria rubra
(662) Dioscorea trifida
(663) Alcea sp.
Expecting value: line 1 column 1 (char 0)
(664) Styphnolobium japonicum
(665) Pipistrellus cf.
Expecting value: line 1 column 1 (char 0)
(666) Hipposideros cf.
Expecting value: line 1 column 1 (char 0)
(667) Rhinolophus alcyone
(668) Uroderma bilobatum
(669) Falco mexicanus
(670) Lagenorhynchus albirostris
(671) canine
Expecting value: line 1 column 1 (char 0)
(672) Bos grunniens
(673) Aglaonema modestum
(674) Aedes aegypti
(675) Penaeus monodon
(676) Citrus volkameriana

In [91]:
len(host_metadata)

2187

In [94]:
df["virus_host_species_tax_id"] = df["host_name_cleaned"].apply(lambda x: host_metadata.get(x).get("species_tax_id") if x in host_metadata else None)

/tmp/ipykernel_1450585/3630995619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["virus_host_species_tax_id"] = df["host_name_cleaned"].apply(lambda x: host_metadata.get(x).get("species_tax_id") if x in host_metadata else None)

In [95]:
df["virus_host_is_vertebrate"] = df["host_name_cleaned"].apply(lambda x: host_metadata.get(x).get("is_vertebrate") if x in host_metadata else None)

/tmp/ipykernel_1450585/3631739729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["virus_host_is_vertebrate"] = df["host_name_cleaned"].apply(lambda x: host_metadata.get(x).get("is_vertebrate") if x in host_metadata else None)

In [96]:
df

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,...,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified,host_name_cleaned,virus_host_species_tax_id,virus_host_is_vertebrate
0,1000373.10,Rosellinia necatrix quadrivirus 1 W1118,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-06T11:05:04.123Z,2025-12-06T11:05:04.123Z,Rosellinia necatrix,77044.0,False
1,1000373.40,Rosellinia necatrix quadrivirus 1 W1075,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-06T08:01:47.037Z,2025-12-06T08:01:47.037Z,Rosellinia necatrix,77044.0,False
2,1000373.50,Rosellinia necatrix quadrivirus 1 W1075,NaN,1000373,10239;2559587;2732396;2732405;2732458;2732540;...,Viruses;Riboviria;Orthornavirae;Duplornavirico...,Viruses,Orthornavirae,Duplornaviricota,Chrymotiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-06T08:01:47.164Z,2025-12-06T08:01:47.164Z,Rosellinia necatrix,77044.0,False
3,1000411.30,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:04:18.329Z,2021-01-23T22:04:18.329Z,Rodent,NaN,None
4,1000411.40,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:06:18.856Z,2021-01-23T22:06:18.856Z,Rodent,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15726,999729.23,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:40:21.986Z,2022-03-12T21:40:21.986Z,Anopheles meraukensis,59157.0,False
15727,999729.24,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:34:20.054Z,2022-03-12T21:34:20.054Z,Anopheles meraukensis,59157.0,False
15728,999729.25,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2022-03-12T21:49:25.104Z,2022-03-12T21:49:25.104Z,Anopheles meraukensis,59157.0,False
15729,999729.35,Leanyer virus AusN16701,NaN,999729,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2022-05-01T01:51:20.496Z,2022-05-01T01:51:20.496Z,Anopheles meraukensis,59157.0,False
15730,999883.50,Lausannevirus 7715,NaN,999883,10239;2732004;2732005;2732007;2732523;2732555;...,Viruses;Varidnaviria;Bamfordvirae;Nucleocytovi...,Viruses,Bamfordvirae,Nucleocytoviricota,Megaviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-16T15:15:58.376Z,2025-12-16T15:15:58.376Z,Acanthamoeba castellanii,5755.0,False

In [108]:
host_metadata["Lycopersicon esculentum"]

KeyError: 'Lycopersicon esculentum'

In [98]:
df.shape

(11382, 93)

In [99]:
df[df["virus_host_species_tax_id"].isna()]

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,...,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified,host_name_cleaned,virus_host_species_tax_id,virus_host_is_vertebrate
3,1000411.3,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:04:18.329Z,2021-01-23T22:04:18.329Z,Rodent,NaN,None
4,1000411.4,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:06:18.856Z,2021-01-23T22:06:18.856Z,Rodent,NaN,None
5,1000411.5,Jacunda virus,NaN,1000411,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T22:06:19.344Z,2021-01-23T22:06:19.344Z,Rodent,NaN,None
6,1000645.3,Ariquemes virus,NaN,1000645,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T21:53:37.675Z,2021-01-23T21:53:37.675Z,Sandfly,NaN,None
7,1000645.4,Ariquemes virus,NaN,1000645,10239;2559587;2732396;2497569;2497571;3151693;...,Viruses;Riboviria;Orthornavirae;Negarnaviricot...,Viruses,Orthornavirae,Negarnaviricota,Bunyaviricetes,...,NaN,NaN,NaN,NaN,NaN,2021-01-23T21:53:37.850Z,2021-01-23T21:53:37.850Z,Sandfly,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15535,935473.5,Rhynchosia yellow mosaic India virus Thiruvana...,NaN,935473,10239;2731342;2732092;2732416;2732424;2732539;...,Viruses;Monodnaviria;Shotokuvirae;Cressdnaviri...,Viruses,Shotokuvirae,Cressdnaviricota,Repensiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-16T15:07:07.341Z,2025-12-16T15:07:07.341Z,Rhynchosia,NaN,False
15536,935473.7,Rhynchosia yellow mosaic India virus Thiruvana...,NaN,935473,10239;2731342;2732092;2732416;2732424;2732539;...,Viruses;Monodnaviria;Shotokuvirae;Cressdnaviri...,Viruses,Shotokuvirae,Cressdnaviricota,Repensiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-16T15:07:11.283Z,2025-12-16T15:07:11.283Z,Rhynchosia,NaN,False
15580,943272.4,Honeysuckle ringspot virus California,NaN,943272,10239;2559587;2732396;2732406;2732463;2788833;...,Viruses;Riboviria;Orthornavirae;Kitrinoviricot...,Viruses,Orthornavirae,Kitrinoviricota,Tolucaviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-18T00:03:53.154Z,2025-12-18T00:03:53.154Z,Honeysuckle,NaN,None
15715,996311.4,Tomato leaf curl Madagascar virus-Menabe [Mada...,NaN,996311,10239;2731342;2732092;2732416;2732424;2732539;...,Viruses;Monodnaviria;Shotokuvirae;Cressdnaviri...,Viruses,Shotokuvirae,Cressdnaviricota,Repensiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-07T16:05:56.968Z,2025-12-07T16:05:56.968Z,Lycopersicon esculentum,NaN,None
15716,996312.3,Tomato leaf curl Madagascar virus-Androy [Mada...,NaN,996312,10239;2731342;2732092;2732416;2732424;2732539;...,Viruses;Monodnaviria;Shotokuvirae;Cressdnaviri...,Viruses,Shotokuvirae,Cressdnaviricota,Repensiviricetes,...,NaN,NaN,NaN,NaN,NaN,2025-12-07T16:05:56.617Z,2025-12-07T16:05:56.617Z,Lycopersicon esculentum,NaN,None

In [107]:
set(df["host_name_cleaned"].unique()) - set(host_metadata.keys())

{'1802)',
 'Abelmoscus esculentus',
 'Abelmoshus esculentus',
 'Abutilon sp.',
 'Acalypha sp.',
 'Adult cotesia',
 'Adult female',
 'Aedeomyia (ochler)',
 'Aeonium sp.',
 'Aeromonas hydrophila;Aeromonas',
 'African green',
 'African penguin',
 'Agapanthus sp.',
 'Aiptasia sp.',
 'Albelmoschus esculentus',
 'Alcea sp.',
 'Alpinia sp.',
 'Althea rosea',
 'Amblyomma (Theileriella)',
 'American white-tailed',
 'Anatid species',
 'Anthurium sp.',
 'Apple tree',
 'Arachis hypogea',
 'Arachis hypogeae',
 'Asgard group',
 'Ash gourd',
 'Ashy-headed sheldgoose',
 'Asian lion',
 'Asteraceae)',
 'Atcc 33303',
 'Bacilluls thuringiensis',
 'Bacillus cereus/thuringiensis',
 'Bacillus pseudalcaliphilus',
 'Bacillus sp.',
 'Bacillus thuringienses',
 'Bambusoideae sp.',
 'Banana',
 'Barley',
 'Bat',
 'Bat colony',
 'Bell pepper',
 'Bermeya goat',
 'Bhk-21',
 'Bing cherry',
 'Bird(acrocephalus schoenbaeus)',
 'Bird(andropadus virens)',
 'Bird(euplectes afra)',
 'Bird(ploceus melanocephalus)',
 'Bird(sylvia curraca)',
 'Bitter gourd',
 'Black-and-white colobus',
 'Blackberry',
 'Blackberry cultivar',
 'Blackberry cv.',
 'Blackcurrant',
 'Blackgram',
 'Blueberry',
 'Bobcat (lynx',
 'Bolomys lasiurus',
 'Bovine',
 'Burkholdria pseudomallei',
 'Camel',
 'Canine',
 'Canna sp.',
 'Capsicum anuum',
 'Cassava plant',
 'Cat',
 'Cattleya hybrid',
 'Cauliflower',
 'Cercopithecus aethiops',
 'Chaereophon aloysiisabaudiae',
 'Chaerephon aloysiisabaudiae',
 'Chaetodipus sp.',
 'Chaoborus cf.',
 'Cherry tomato',
 'Cherry valley',
 'Chile pepper',
 'Chili pepper',
 'Chilli',
 'Chinese fire',
 'Chinese mitten-handed',
 'Chlorocebus sp.',
 'Chondrichthyes and',
 'Chrysanthemum x',
 'Citrus cv.',
 'Cluster bean',
 'Cocoa',
 'Colwellia psychrerythaea',
 'Common marmoset',
 'Condonopsis lanceolata',
 'Cow parsley',
 'Cowpea',
 'Croton bonplandianum',
 'Crown',
 'Cryptoblepharus (Ablepharus)',
 'Cucurbit',
 'Culex (Melanoconion)',
 'Culex (lophoceraomyia)',
 'Culex (melanoconion)',
 'Culexlophoceratomyia',
 'Cultivated blackberry',
 'Cupsicum annum',
 'Cv. rio',
 'Dabbling duck',
 'Dairy cow',
 'Desmodium sp.',
 'Digitaria sp.',
 'Diodia sp.',
 'Dipteran(coquillettidia maculipennis)',
 'Dromedary camel',
 'Duck',
 'E. coli',
 'E. coli;',
 'Eclipta',
 'Elderberry',
 'Elderberry (sambucus',
 'Embryonated chicken',
 'Epiphyllum sp.',
 'Epomophorus sp.',
 'Equine',
 'Erwinia amylovora;',
 'Escherichia coli,',
 'Eurasian jackdaw',
 'Eureka lemon',
 'European starling',
 'Faba bean',
 'Fabaceae)',
 'Fenugreek',
 'Feral pigeon',
 'Fig',
 'Finch',
 'Firespike',
 'Florida panther',
 'Forest musk',
 'Fox',
 'Fragaria (strawberry)',
 'Fragaria x',
 'Free-living grapevine',
 'French bean',
 'Frog',
 'Giardia',
 'Glory bower',
 'Gopherus sp.',
 'Gordonia sp.',
 'Grapevine',
 'Grapevine (chardonel)',
 'Grey crowned',
 'Groundnut',
 'Hackberry',
 'Hamster',
 'Hard ticks',
 'Hermit crab',
 'Heterodontonyx sp.',
 'Hibiscus spp.',
 'Hipposideros cf.',
 'Hipposideros commersoni',
 'Homo sapiens,',
 'Honeysuckle',
 'Hoplichthys sp.',
 'Horse brain',
 'Horse cutaneous',
 'Horseradish',
 'Hot pepper',
 'Human, Homo',
 'Hybrid sugar',
 'Hyperhalophilic archaea',
 'Hypochaeris sp.',
 'Infected scophthalmus',
 'Iris',
 'Itc0528',
 'Ixodes (Trichotoixodes)',
 'Jacquemontia sp.',
 'Jasmine',
 'Johnson grass',
 'Jujube',
 'Jute mallow',
 'Kinnow mandarin',
 'Klebsiella oxytoca;',
 'Large cardamom',
 'Lebeckia sp.',
 'Lepidoptera mix',
 'Lettuce',
 'Leucoraja erinacea',
 'Lily',
 'Lisianthus',
 'Lisianthus plant',
 'Luffa acutungula',
 'Luffa cylindrica',
 'Lycopersicon esculentum',
 'Macroptilium sp.',
 'Macropusrufus',
 'Macuna spp.',
 'Malvaceae)',
 'Malvastrum sp.',
 'Mandevilla sp.',
 'Marigold',
 'Marine snail',
 'Melochia sp.',
 'Melon',
 'Mesophilic methanobacterium',
 'Methanobacterium thermoautotrophicum',
 'Methanophagales (anme-1',
 'Midges',
 'Miniopterus cf.',
 'Miniopterus schreibersi',
 'Mink',
 'Miscanthus sp.',
 'Mocis sp.',
 'Monitor lizard',
 'Monkey',
 'Mont1 megavirus',
 'Morganella sp.',
 'Mosquito',
 'Motherwort',
 'Mouse (sentinel)',
 'Mulberry',
 'Musa aab',
 'Musa spp.',
 'Mycobacterium smegamatis',
 'Mycobacterium smegamtis',
 'Mycobacterium smegmatic',
 'Mycobacteruim smegmatis',
 'Mycobacterum smegmatis',
 'Mycolicobacterium smegmatis',
 'N. benthamiana',
 'Neognath bird',
 'Nerine hybrid',
 'Nicotiana bethamiana',
 'North american',
 'Northern red-backed',
 'Ochlerotatus cf.',
 'Okra oth116',
 'Olea europea',
 'Olive',
 'Olive tree',
 'Onagraceae)',
 'Ophicephalus struatus',
 'Opossum',
 'Oriental Magpie',
 'Palaemonetes sp.',
 'Palm civet',
 'Palmetto bug',
 'Pangolin',
 'Panicum maximum',
 'Paracoccus sp.',
 'Passion fruit',
 'Pavonia sp.',
 'Pectobactorium corotovorum',
 'Pelargonium sp.',
 'Pepper',
 'Persicivirga sp.',
 'Petunia x',
 'Phlebotomus (Larroussius)',
 'Phlebotomus (larroussius)',
 'Phoenicoparrus minor',
 'Pigeon',
 'Pineapple plants',
 'Pipistrellus cf.',
 'Plantain',
 'Pooled ticks',
 'Porcine',
 'Potato (solanum',
 'Praomys sp.',
 'Prochlorococcus MED4',
 'Proteus sp.',
 'Pseduomonas aeruginosa',
 'Pseudcmonas fluorescens',
 'Pumpkin sp.',
 'Putative fungus',
 'Pyrenacantha sp.',
 'Quail',
 'Radish cultivar',
 'Rana esculenta',
 'Rat',
 'Rhesus macaque',
 'Rhizosphagus sp.',
 'Rice',
 'Rnai-transgenic tomato',
 'Rodent',
 'Rose',
 'Rose cv.',
 'Rousettus leschenaulti',
 'Rudbeckia sp.',
 'Ruttus norvegicus',
 'Saccharum genotype',
 'Saguaro',
 'Sand fly',
 'Sandfly',
 'Scrophulariaceae)',
 'Sentinel hamster',
 'Sentinel mouse',
 'Serratia sp.',
 'Shigella boydii;',
 'Shigella dysenteriae,',
 'Shigella flexneri,',
 'Shigella flexneri;',
 'Shrew',
 'Shrimp',
 'Sida spp.',
 'Sidastrum sp.',
 'Sikkim rat',
 'Snake melon',
 'Soft-shelled turtle',
 'Solanaceae sp.',
 'Solanum licopersicum',
 'Solenopsis invicta;',
 'Sorghum x',
 'Spartina sp.',
 'Spirurian nematodes',
 'Sponge gourd',
 'Sporobolus sp.',
 'Squirrel monkey',
 'Stenella sp.',
 'Stephanocircus sp.',
 'Streptomyces albus;',
 'Suckling mouse',
 'Sugarcane cultivar',
 'Sugarcane r570',
 'Swine',
 'Synechococcus str.',
 'TN10',
 'Tasmanian tick',
 'Tea tussork',
 'Tetterwort',
 'Tick',
 'Tilliaceae)',
 'Tobacco',
 'Tojo &',
 'Tomate',
 'Tomato cv.',
 'Tomato plant',
 'Trichomonas vaginali',
 'Triumfetta sp.',
 'Unidentified gerridae',
 'Unidentified hippoboscidae',
 'Uraeginthus granatina',
 'Uria sp.',
 'Vampire bat',
 'Vanilla x',
 'Vasconcellea x',
 'Velvet bean',
 'Verbena sp.',
 'Vole',
 'Water chestnut',
 'Weed',
 'Western common',
 'Wheat',
 'White kangaroo',
 'Wild horse',
 'Wild sunflower',
 'Willdenowia sp.',
 'Wissadula sp.',
 'Worker termites',
 'Yacon',
 'Yam bean',
 'Zantedeschia spp.',
 'Zinnia sp.',
 'Ziziphus jujube',
 'Zucchini',
 'asymptomatic piglets',
 'avian pathogenic',
 'bat',
 'bird',
 'black bear',
 'black goat',
 'black-and-white colobus',
 'blackberry cv.',
 'camel',
 'canine',
 'carf',
 'cattle, wild',
 'chili',
 'cricket',
 'darcopsis wallaby',
 'domestic sheep',
 'dove',
 'dromedary',
 'duck',
 'enterotoxigenic Escherichia',
 'equine',
 'fall chinook',
 'feline',
 'feral pigeons',
 'ferret badger',
 'finch',
 'fruit bat',
 'goose embryo',
 'ground squirrel',
 'hard ticks',
 'human foreskin',
 'hybrid snakehead',
 'interferon-alpha/beta/gamma receptor',
 'laying duck',
 'lettuce',
 'magpie-robin',
 'mallard duck',
 'masked palm',
 'methicillin-resistant Staphylococcus',
 'microbat',
 'mink',
 'mosquito',
 'mosquitoes (from',
 'neognath bird',
 'night-heron',
 'opossum',
 'orangutan',
 'ovine',
 'pathenogenic Salmonella',
 'peach cv.',
 'penguin',
 'pepper',
 'pigeon',
 'pool of',
 'porcine',
 'pronghorn antelope',
 'pteropid bat',
 'raspberry',
 'raspberry plant',
 'rat',
 'rat primary',
 'rice',
 'ring-necked pheasant',
 'sentinel hamster',
 'sentinel mice',
 'sentinel monkey',
 'sentinel mouse',
 'shiga toxin-producing',
 'short-nosed fruit',
 'snake-associated nematodes',
 'sparrow',
 'suckling newborn',
 'swine',
 'tamarin monkey',
 'taro (Colocasia',
 'unidentified Gerridae',
 'unidentified Polydesmidae',
 'unidentified Tabanidae',
 'unknown alphaproteobacteria',
 'warthog',
 'wheat',
 'white-eye',
 'whitetail deer',
 'wigeon',
 'wild bird',
 'wild birds',
 'wild duck',
 'wild rat',
 'yaks',
 'zucchini cv.'}